config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: "users/invitations",
    registrations: "users/registrations"
  }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :credit_cards, only: [:index, :new, :create, :edit, :update] do
    member do
      patch 'close'
      patch 'activate'
      patch 'deactivate'
    end
  end

  resources :categories, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      patch 'activate'
      patch 'deactivate'
    end
  end

  resources :expenses, only: [:index, :create]

  resources :users, only: [:create, :new, :index, :show, :edit, :update]
  post '/users/:id/reinvite', to: 'users#reinvite', as: 'reinvite'

  devise_scope :user do
    delete '/admin_users/:id', to: 'users/registrations#admin_destroy_user', :as => :admin_destroy_user
  end
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  has_many :expenses
  belongs_to :company

  def last_digits
    number.to_s.length <= 4 ? number : number.to_s.slice(-4..-1)
  end

  def mask
    "XXXX-XXXX-XXXX-#{last_digits}"
  end
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController

  def index
    @credit_cards = policy_scope(CreditCard).order("
      CASE
        WHEN status = 'Active' THEN '1'
        WHEN status = 'Not active' THEN '2'
        WHEN status = 'Closed' THEN '3'
      END
    ")

  end

  def new
      @credit_card = CreditCard.new
      authorize @credit_card
  end

  def create
      @credit_card = CreditCard.new(credit_card_params)
      @credit_card.company = current_user.company
      if @credit_card.save!
        flash[:notice] = "Credit card has been successfully added"
        redirect_to credit_cards_path
      else
        flash[:alert] = "Something went wrong"
        render :new
      end
      authorize @credit_card
  end

  def edit
    @credit_card = CreditCard.find(params[:id])
    authorize @credit_card
    if @credit_card.status != "Closed"
    else
    redirect_to credit_cards_path
    end
  end

  def update
    @credit_card = CreditCard.find(params[:id])
    authorize @credit_card
    @credit_card.update(credit_card_params)
    redirect_to credit_cards_path
  end

  def activate
    @credit_card = CreditCard.find(params[:id])
    authorize @credit_card
    if (current_user.company.credit_cards.where(status: "Active")).count == 0
      @credit_card.update(status: "Active")
      flash[:notice] = "Credit card has been activated"
      redirect_to credit_cards_path
    else
      flash[:alert] = "Only one credit card can be active at the same time"
      redirect_to credit_cards_path
    end
  end

   def deactivate
    @credit_card = CreditCard.find(params[:id])
    authorize @credit_card
    @credit_card.update(status: "Not active")
    flash[:alert] = "Credit card has been deactivated"
    redirect_to credit_cards_path
  end

  def close
    @credit_card = CreditCard.find(params[:id])
    authorize @credit_card
    @credit_card.update(status: "Closed")
    if @credit_card.save
      flash[:notice] = "Credit card has been closed"
      redirect_to credit_cards_path
    else
      flash[:alert] = "Something went wrong"
      redirect_to credit_cards_path
    end
  end

  private

  def credit_card_params
    params.require(:credit_card).permit(:number, :credit_card_type, :exp_date, :billing_day, :status)
  end
end

app/views/credit_cards/_form.html.erb
<% title "Credit cards" %>
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="box-outter">
        <div class="box-inner">
          <%= simple_form_for @credit_card do |f| %>
          <%= f.input :number %>
          <%= f.input :credit_card_type %>
          <%= f.input :exp_date, label: "Expiry date (mm/yy)" %>
          <%= f.input :billing_day %>
          <%= f.input :status, input_html: { value: 'Not active' }, as: :hidden %>
          <div class="form-actions">
           <%= f.submit class: "btn-spad" %>
           <%= link_to "Cancel", :back, class: "btn-spad-cancel" %>
         </div>

         <% end %>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/credit_cards/edit.html.erb
<% title "Credit cards" %>
<%= render 'form' %>

app/views/credit_cards/index.html.erb
<% title "Credit cards" %>
 <div class="container">
 <h4>Credit Cards</h4>
  <div class="box-outter">
    <div class="box-inner">
    <div class="padded-bottom">
      <% if policy(@credit_cards).new? %>
        <%= link_to "Add a credit card", new_credit_card_path, class: "btn-spad" %>
      <% end %>
    </div>

      <div class="table-responsive">
        <table class="table category-table">
          <thead>
            <tr>
              <th>CCN</th>
              <th>Type</th>
              <th>Expiry date</th>
              <th>Cycle's last day</th>
              <th>Status</th>
              <% if policy(@credit_cards).activate? %>
                <th colspan="2" class="text-center">Controls</th>
              <% else %>
              <% end %>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @credit_cards.each do |c| %>
            <tr>
              <td><%= c.mask %></td>
              <td><%= c.credit_card_type %></td>
              <td><%= c.exp_date %></td>
              <td><%= c.billing_day %></td>
              <td><%= c.status %></td>

              <% if policy(@credit_cards).activate? %>
                <% if c.status == "Closed" %>
                  <td></td>
                <% elsif (c.status != "Active") %>
                  <td><%= link_to "Activate", activate_credit_card_path(c), method: :patch, class: "btn-spad-green" %></td>
                <% else %>
                  <td><%= link_to "Deactivate", deactivate_credit_card_path(c), method: :patch, class: "btn-spad-green" %></td>
                <% end %>

                <% if c.status == "Closed" %>
                  <td></td>
                <% else %>
                  <td><%= link_to edit_credit_card_path(c), class: "btn-spad-fa" do %>
                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    <% end %>
                  </td>
              <% end %>


                <% if (c.status == "Closed") || (c.status == "Active") %>
                  <td></td>
                <% else %>
                  <td><button type="button" class="btn-spad-fa" data-toggle="modal" data-target="#exampleModal<%=c.id%>"><i class="fa fa-times" aria-hidden="true"></i></button></td>

                  <div class="modal fade" id="exampleModal<%=c.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModal">Confirmation window</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          Are you sure you want to close this credit card? You cant open a closed card.
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn-spad-cancel" data-dismiss="modal">Cancel</button>
                          <%= link_to "Yes, I am sure", close_credit_card_path(c), method: :patch, class: "btn-spad" %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/credit_cards/new.html.erb
<% title "Credit cards" %>
<%= render 'form' %>