config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: "users/invitations",
    registrations: "users/registrations"
  }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :credit_cards, only: [:index, :new, :create, :edit, :update] do
    member do
      patch 'close'
      patch 'activate'
      patch 'deactivate'
    end
  end

  resources :categories, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      patch 'activate'
      patch 'deactivate'
    end
  end

  resources :expenses, only: [:index, :create]

  resources :users, only: [:create, :new, :index, :show, :edit, :update]
  post '/users/:id/reinvite', to: 'users#reinvite', as: 'reinvite'

  devise_scope :user do
    delete '/admin_users/:id', to: 'users/registrations#admin_destroy_user', :as => :admin_destroy_user
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :company

#   after_create :send_welcome_email
  has_many :expenses

  def admin?
    admin
  end

  def has_expenses?
    if self.expenses.size > 0
      true
    else
      false
    end
  end

  # soft delete implementation st
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  # ensure user account is active
  def active_for_authentication?
    super && !deleted_at
  end

  # provide a custom message for a deleted account
  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  # enf of soft delete requirements

  def role(user)
     if user.admin
      return "Admin"
      else return "User"
      end
  end
  mount_uploader :portrait, PortraitUploader
  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end


end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController

 before_filter :configure_permitted_parameters, if: :devise_controller?



  def after_invite_path_for(resource)
    users_path
  end


  def after_sign_up_path_for(resource)
    #super(resource)
    expenses_path
  end

  def after_sign_in_path_for(resource)
    #super(resource)
    expenses_path
  end


  private

   def invite_params
      params.require(:user).permit(:name, :email, :invitation_token, :company_id, :status, :first_name, :last_name, :status)
   end

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:accept_invitation) do |u|
      u.permit(:last_name, :first_name, :email, :password, :password_confirmation, :invitation_token, :status)
  end

end


end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  # Next : it would be better to keep this version with super,
  # though NP can't find a solution to include company_id into the params before passing to super.
  # def create
  #   byebug
  #   @company = Company.new
  #   @company.name = params[:company_name]
  #   @company.save
  #   super
  #   @user.company_id = @company.id
  # end

  def create
    @company = Company.new
    @company.name = params[:company_name]
    @company.save

    build_resource(sign_up_params.merge(company_id: @company.id, admin: true))

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  def admin_destroy_user
    resource = User.find(params[:id])
    authorize resource

    resource.status = "deleted"
    resource.soft_delete
    # Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to users_path }

  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :company_name, :company_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :first_name, :last_name, :company_name])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    #super(resource)
    expenses_path
  end

  def after_sign_in_path_for(resource)
    #super(resource)
    expenses_path
  end
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
      @users = policy_scope(User).order(created_at: :desc)
      @user = User.new
  end

def show
  set_user
  @company = Company.find(@user.company_id)
  authorize @user
end
  # def create
  #   @user = User.new(user_params)
  #   @user.company_id = current_user.company_id
  #   @user.save
  #   redirect_to users_path
  # end

  def reinvite
    @user = User.find(params[:id])
    @user.deleted_at = nil
    @user.status = 'invited'
    @user.invite!(current_user)
    redirect_to users_path
    authorize @user
  end

  def edit
    set_user
    authorize @user

  end

  def update
    set_user
    @user.save
    @user.update(user_params)
    redirect_to user_path(@user)
    authorize @user
  end


  # def destroy
  #   set_user
  #   @user.destroy
  #   redirect_to users_path
  #   authorize @user
  # end

  def set_user
     @user = User.find(params[:id])
  end

private

  def user_params
    params.require(:user).permit(:email, :id, :first_name, :last_name, :portrait, :portrait_cache)
  end

end

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<% title "Edit profile" %>
<div class="container">
  <div class="box-outter">
    <div class="box-inner">
      <%= simple_form_for [@user] do |f| %>
        <%= f.input :first_name %><br>
        <%= f.input :last_name %><br>
         <%= f.input :email, required: true, autofocus: true %>
        <%= f.input :portrait %>
        <%= f.input :portrait_cache, as: :hidden %>
        <div class="form-actions">
          <%= f.submit "Save changes", class: "btn-spad" %>
          <%= link_to "Cancel", root_path, class: "btn-spad-cancel" %>
    </div>



      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<% title "Team" %>
<div class="container">
  <div class="row">
    <div class="box-outter">
      <% if policy(User).reinvite? %>
      <div class="box-inner">
        <h3><%= t "devise.invitations.new.header" %></h3>

        <%= simple_form_for :user, url: user_invitation_path, html: { method: :post} do |f| %>

        <% User.invite_key_fields.each do |field| -%>
        <%= f.input field %>
        <% end %>
        <input name="user[company_id]" type="hidden" value="<%= current_user.company_id %>">
        <input name="user[status]" type="hidden" value="invited">
        <%= f.button :submit, t("devise.invitations.new.submit_button"), class: "btn-spad" %>
        <% end %>
      </div>
      <% end %>
      <div class="box-inner">
        <% if policy(User).index? %>
<h4>Active users</h4>
        <div class="table-responsive">
          <table class="table category-table">
            <thead>
              <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Status</th>
                <th>Role</th>
                <% if policy(User).reinvite? %>
                <th>Invitation sent</th>
                <th colspan="2" class="text-center">Controls</th>
                <% end %>
              </tr>
            </thead>
            <% @users.each do |user| %>
            <% if user.status != 'deleted' %>
            <tr>
              <td><%= user.first_name %></td>
              <td><%= user.last_name %></td>
              <td><%= user.email %></td>
              <td><%= user.status %></td>
              <td><%= user.role(user) %></td>
              <% if policy(user).reinvite? %>
              <% if user.invitation_sent_at.nil? %>
              <td><%= user.invitation_sent_at %></td>
              <% else %>
              <td><%= user.invitation_sent_at.strftime("%d/%m/%Y") %></td>
              <% end %>
              <td>
                <%= link_to 'Re-invite', reinvite_path(user), method: :post, class: "btn-spad-green", style: "white-space: nowrap;" %>
                <% end %>
              </td>
              <% if policy(user).destroy? %>
              <td><button type="button" class="btn-spad-fa" data-toggle="modal" data-target="#exampleModal<%=user.id%>"><i class="fa fa-times" aria-hidden="true"></i></button></td>
              <% end %>
            </tr>
            <% end %>
            <% end %>
          </table>
        </div>
<h4>Deleted users</h4>
       <div class="table-responsive">
          <table class="table category-table">
            <thead>
              <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Status</th>
                <th>Role</th>
                <% if policy(User).reinvite? %>
                <th>Invitation sent</th>
                <th colspan="2" class="text-center">Controls</th>
                <% end %>
              </tr>
            </thead>
            <% @users.each do |user| %>
            <% if user.status == 'deleted' %>
            <tr>
              <td><%= user.first_name %></td>
              <td><%= user.last_name %></td>
              <td><%= user.email %></td>
              <td><%= user.status %></td>
              <td><%= user.role(user) %></td>
              <% if policy(user).reinvite? %>
              <% if user.invitation_sent_at.nil? %>
              <td><%= user.invitation_sent_at %></td>
              <% else %>
              <td><%= user.invitation_sent_at.strftime("%d/%m/%Y") %></td>
              <% end %>
              <td>
                <%= link_to 'Re-invite', reinvite_path(user), method: :post, class: "btn-spad-green", style: "white-space: nowrap;" %>
                <% end %>
              </td>
              <% if policy(user).destroy? %>
              <td><button type="button" class="btn-spad-fa" data-toggle="modal" data-target="#exampleModal<%=user.id%>"><i class="fa fa-times" aria-hidden="true"></i></button></td>
              <% end %>
            </tr>
            <% end %>
            <% end %>
          </table>
        </div>



        <% end %>
      </div>

    </div>
  </div>
</div>

<% @users.each do |user| %>
<div class="modal fade" id="exampleModal<%=user.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModal">Confirmation window</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this user?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn-spad-cancel" data-dismiss="modal">Cancel</button>
        <%= link_to "Yes, I am sure", admin_destroy_user_path(user), method: :delete, class: "btn-spad" %>

      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/reinvite.html.erb
reinvite.html.erb

app/views/users/show.html.erb
<% title "Profile" %>
<div class="container">
  <div class="box-outter">
    <div class="box-inner">
      <p><strong>First Name :</strong> <%= @user.first_name %></p>
      <p><strong>Last Name :</strong> <%= @user.last_name %></p>
      <p><strong>Email :</strong>  <%= @user.email %></p>
      <p><strong>Type :</strong>  <%= @user.role(@user) %></p>
      <%= cl_image_tag @user.portrait, crop: :fill, class: "avatar-large-profile" %>
      <br>


      <p class="margined-bottom">
        <div class="form-actions">
      <%= link_to 'Edit profile', edit_user_path(@user), class: "btn-spad-green", style: "white-space: nowrap;" %>
      <%= link_to 'Change Password', edit_user_registration_path, class: "btn-spad-green", style: "white-space: nowrap;" %>

        </div>
      </p>
    </div>
  </div>
</div>