config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: "users/invitations",
    registrations: "users/registrations"
  }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :credit_cards, only: [:index, :new, :create, :edit, :update] do
    member do
      patch 'close'
      patch 'activate'
      patch 'deactivate'
    end
  end

  resources :categories, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      patch 'activate'
      patch 'deactivate'
    end
  end

  resources :expenses, only: [:index, :create]

  resources :users, only: [:create, :new, :index, :show, :edit, :update]
  post '/users/:id/reinvite', to: 'users#reinvite', as: 'reinvite'

  devise_scope :user do
    delete '/admin_users/:id', to: 'users/registrations#admin_destroy_user', :as => :admin_destroy_user
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert", style="position: absolute; width: 100%; z-index: 1">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert", style="position: absolute; width: 100%; z-index: 1">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png", width: '500' %>
  <% end %>

  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if current_page?(root_path) %>
    <!-- Profile picture and dropdown -->
    <a href="" class="navbar-wagon-item navbar-wagon-link">Products</a>

    <a href="" class="navbar-wagon-item navbar-wagon-link">Customers</a>

    <a href="" class="navbar-wagon-item navbar-wagon-link">Price</a>

    |
    <% end %>

    <% if user_signed_in? %>


    <div class="navbar-wagon-item">
      <div class="dropdown">

        <a href="" class="navbar-wagon-item navbar-wagon-link dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">Menu</a>

        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to expenses_path do %>
            <i class="fa fa-money"></i>  <%= t(".profile", default: "Expenses") %>
            <% end %>
          </li>
          <li>
            <%= link_to credit_cards_path do %>
            <i class="fa fa-credit-card"></i>  <%= t(".profile", default: "Credit Cards") %>
            <% end %>
          </li>
          <li>
            <%= link_to categories_path do %>
            <i class="fa fa-files-o"></i>  <%= t(".profile", default: "Categories") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
   <% if current_user.admin? %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <a href="" class="navbar-wagon-item navbar-wagon-link dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">Settings</a>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to users_path do %>
            <i class="fa fa-users"></i>  <%= t(".profile", default: "Team members") %>
            <% end %>
          </li>

        </ul>
      </div>
    </div>
       <% end %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if user_signed_in? %>
        <% if !current_user.portrait? %>
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>

        <%= cl_image_tag current_user.portrait, class: 'avatar-bordered', crop: :fill, id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>
        <% else %>
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to user_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "My Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>

    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <% if user_signed_in? %>
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to root_path do %>
          <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
          <% end %>
        </li>
        <li>
          <%= link_to expenses_path do %>
          <i class="fa fa-money"></i>  <%= t(".profile", default: "Expenses") %>
          <% end %>
        </li>
        <li>
          <%= link_to credit_cards_path do %>
          <i class="fa fa-credit-card"></i>  <%= t(".profile", default: "Credit Cards") %>
          <% end %>
        </li>
        <li>
          <%= link_to categories_path do %>
          <i class="fa fa-files-o"></i>  <%= t(".profile", default: "Categories") %>
          <% end %>
        </li>
        <li>
          <%= link_to users_path do %>
          <i class="fa fa-users"></i>  <%= t(".profile", default: "Team members") %>
          <% end %>
        </li>

        <li>
          <%= link_to user_path(current_user) do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "My Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>

    <% else %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>

app/views/shared/old_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
<!--     <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Notification -->
<!--     <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
    <div class="badge-container">
      <i class="fa fa-envelope-o"></i>
      <div class="badge badge-blue">3</div>
    </div>
    <% end %> -->

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">



            <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>


        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to expenses_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Expenses") %>
            <% end %>
          </li>
          <li>
            <%= link_to credit_cards_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Credit Cards") %>
            <% end %>
          </li>
          <li>
            <%= link_to categories_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Categories") %>
            <% end %>
          </li>
          <% if current_user.admin? %>
            <li>
              <%= link_to users_path do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Team members") %>
              <% end %>
          </li>
          <% end %>

          <li>
            <%= link_to user_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "My Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
<!--     <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %> -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
<div class="navbar-wagon-item hidden-md hidden-lg">

    <% if user_signed_in? %>

    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to expenses_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Expenses") %>
            <% end %>
          </li>
          <li>
            <%= link_to credit_cards_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Credit Cards") %>
            <% end %>
          </li>
          <li>
            <%= link_to categories_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Categories") %>
            <% end %>
          </li>
          <li>
            <%= link_to users_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Team members") %>
            <% end %>
          </li>

          <li>
            <%= link_to user_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "My Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
      </ul>
    </div>
    <% end %>
  </div>
</div>