config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: "users/invitations",
    registrations: "users/registrations"
  }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :credit_cards, only: [:index, :new, :create, :edit, :update] do
    member do
      patch 'close'
      patch 'activate'
      patch 'deactivate'
    end
  end

  resources :categories, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      patch 'activate'
      patch 'deactivate'
    end
  end

  resources :expenses, only: [:index, :create]

  resources :users, only: [:create, :new, :index, :show, :edit, :update]
  post '/users/:id/reinvite', to: 'users#reinvite', as: 'reinvite'

  devise_scope :user do
    delete '/admin_users/:id', to: 'users/registrations#admin_destroy_user', :as => :admin_destroy_user
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :expenses
  belongs_to :company
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = policy_scope(Category).order("
      CASE
        WHEN status = 'Active' THEN '1'
        WHEN status = 'Not active' THEN '2'
      END
    ")
  end

  def new
      @category = Category.new
      authorize @category
  end

  def create
      @category = Category.new(category_params)
      @category.company = current_user.company
      if @category.save!
        flash[:notice] = "Category has been successfully added"
        redirect_to categories_path
      else
        flash[:alert] = "Something went wrong"
        render :new
      end
      authorize @category
  end

  def edit
    @category = Category.find(params[:id])
    authorize @category
  end

  def update
    @category = Category.find(params[:id])
    authorize @category
    @category.update(category_params)
    redirect_to categories_path
  end

  def activate
    @category = Category.find(params[:id])
    authorize @category
    @category.update(status: "Active")
    flash[:notice] = "Category has been activated"
    redirect_to categories_path
  end

   def deactivate
    @category = Category.find(params[:id])
    authorize @category
    @category.update(status: "Not active")
    flash[:alert] = "Category has been deactivated"
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :status)
  end
end

app/views/categories/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="box-outter">
        <div class="box-inner">
          <%= simple_form_for @category do |f| %>
            <%= f.input :name, label: "Category name" %>
            <%= f.input :status, input_html: { value: 'Active' }, as: :hidden %>

            <div class="form-actions">
             <%= f.submit class: "btn-spad" %>
             <%= link_to "Cancel", :back, class: "btn-spad-cancel" %>
           </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<% title "Categories" %>
<%= render 'form' %>

app/views/categories/index.html.erb
<% title "Categories" %>
<div class="container">
<h4>Categories</h4>
  <div class="box-outter">
    <div class="box-inner">
  <div class="padded-bottom"><% if policy(@categories).new? %>
    <%= link_to "Add a category", new_category_path, class: "btn-spad" %>
  <% end %></div>
    <div class="table-responsive">
      <table class="table category-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Status</th>
              <th class="text-right">Amount</th>
              <th class="text-center">Number of entries</th>
              <% if policy(@categories).new? %>
                <th colspan="2" class="text-center">Controls</th>
              <% else %>
              <% end %>
            </tr>
          </thead>
          <tbody>
              <% @categories.each do |c| %>
                <% if c.status == "Not active" %>
                  <tr>
                <% else %>
                  <tr>
                <% end %>
                  <td><p><%= c.name %></p></td>
                  <td><p><%= c.status %><p></td>
                  <td class="text-right"><p>€<%= Money.new(c.expenses.sum(:amount_cents), 'EUR') %></p></td>
                  <td class="text-center" ;"><p><%= c.expenses.count %></p></td>
                  <% if policy(@categories).new? %>
                    <% if (c.status != "Active") %>
                      <td class="padded-top-table"><%= link_to "Activate", activate_category_path(c), method: :patch, class: "btn-spad-green" %></td>
                    <% else %>
                      <td><%= link_to "Deactivate", deactivate_category_path(c), method: :patch, class: "btn-spad-green" %></td>
                    <% end %>
                  <td><%= link_to edit_category_path(c), class: "btn-spad-fa" do %>
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                      <% end %></td>
                  <% end %>
                </tr>
              <% end %>
          </tbody>
        </table>
        </div>
      </div>
    </div>
</div>

app/views/categories/new.html.erb
<% title "Categories" %>
<%= render 'form' %>